version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  script:
    build: .
    command: python manage.py start_script
    volumes:
      - .:/app
    restart: always
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GSHEETS_URL=https://docs.google.com/spreadsheets/d/1p3YOopCH996XAShh8Op7M6lb184rE7D5xjHJiYzmLNs/edit?usp=sharing
      - GSHEETS_LIST=Лист1
      - BOT_TOKEN=12XXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXX
      - CHAT_ID=72XXXXXXX
      - SCHEDULE_TIME=5
      - PYTHONUNBUFFERED=1
    depends_on:
      - web