version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  script:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py start_script
      "
    volumes:
      - .:/app
    restart: always
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db