# Generated by Django 4.1.1 on 2022-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='заказ №')),
                ('price', models.FloatField(verbose_name='стоимость,$')),
                ('delivery_date', models.DateField(verbose_name='срок поставки')),
                ('price_in_rub', models.FloatField(verbose_name='стоимость в руб.')),
            ],
        ),
    ]
